//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HEYS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLHastaneBolum
    {
        public int BolumID { get; set; }
        public Nullable<int> PersonelId { get; set; }
        public Nullable<int> BagliEnvanter { get; set; }
        public string BolumIsmi { get; set; }
        public Nullable<int> PersonelSayisi { get; set; }
        public Nullable<int> DahiliNo { get; set; }
    
        public virtual TBLEnvanter TBLEnvanter { get; set; }
        public virtual TBLPersonel TBLPersonel { get; set; }
    }
}
