//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HEYS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLTeknikServis
    {
        public int ArizaID { get; set; }
        public Nullable<int> EnvanterId { get; set; }
        public string UrunIsmi { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<System.DateTime> GelisTarihi { get; set; }
        public string GelisSebebi { get; set; }
        public string Durum { get; set; }
        public Nullable<System.DateTime> CikisTarihi { get; set; }
    
        public virtual TBLEnvanter TBLEnvanter { get; set; }
    }
}
