//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneEnvanterYonetimSistemi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKullanıcı
    {
        public int ID { get; set; }
        public Nullable<int> YetkiDurumu { get; set; }
        public string TCNo { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Parola { get; set; }
        public string Mail { get; set; }
        public string DahiliNo { get; set; }
        public string CalistigiBirim { get; set; }
        public byte[] Fotograf { get; set; }
    
        public virtual TBLYetki TBLYetki { get; set; }
    }
}
